config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :stages

  resources :cycling_teams do 
  		resources :riders
 	end

  get 'welcome/index'
  get 'welcome/yellow'
  get 'welcome/green'
  get 'welcome/white'
  get 'welcome/polka'
  get 'welcome/preview'
     
  root 'welcome#index'

 end

app/models/cycling_team.rb
class CyclingTeam < ActiveRecord::Base
 has_many :riders
end

app/models/rider.rb
class Rider < ActiveRecord::Base
  belongs_to :cycling_team
end

app/models/stage.rb
class Stage < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
  
end

app/controllers/cycling_teams_controller.rb
class CyclingTeamsController < ApplicationController
    before_action :set_cycling_team, only: [:tdf_teams, :show, :edit, :update, :destroy]

  # GET /cycling_teams
  # GET /cycling_teams.json
  def index
    @cycling_teams = CyclingTeam.all
  end
  
  # GET /cycling_teams/1
  # GET /cycling_teams/1.json
  def show
 	#render(text: "De View voor deze actie bestaat nog niet")
  	@cycling_team = CyclingTeam.find(params[:id])
  end

  # GET /cycling_teams/new
  def new
    @cycling_team = CyclingTeam.new
  end

  # GET /cycling_teams/1/edit
  def edit
  end

  # POST /cycling_teams
  # POST /cycling_teams.json
  def create
    @cycling_team = CyclingTeam.new(cycling_team_params)

    respond_to do |format|
      if @cycling_team.save
        format.html { redirect_to @cycling_team, notice: 'Cycling team was successfully created.' }
        format.json { render :show, status: :created, location: @cycling_team }
      else
        format.html { render :new }
        format.json { render json: @cycling_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cycling_teams/1
  # PATCH/PUT /cycling_teams/1.json
  def update
    respond_to do |format|
      if @cycling_team.update(cycling_team_params)
        format.html { redirect_to @cycling_team, notice: 'Cycling team was successfully updated.' }
        format.json { render :show, status: :ok, location: @cycling_team }
      else
        format.html { render :edit }
        format.json { render json: @cycling_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cycling_teams/1
  # DELETE /cycling_teams/1.json
  def destroy
    @cycling_team.destroy
    respond_to do |format|
      format.html { redirect_to cycling_teams_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cycling_team
      @cycling_team = CyclingTeam.find(params[:id])
    end
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def cycling_team_params
      params.require(:cycling_team).permit(:id, :name, :description, :logo, :tdf)
    end
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  before_action :set_rider, only: [:show, :edit, :update, :destroy]

  # GET /riders
  # GET /riders.json
  def index
    @riders = Rider.all
  end

  # GET /riders/1
  # GET /riders/1.json
  def show
  end

  # GET /riders/new
  def new
    @rider = Rider.new
  end

  # GET /riders/1/edit
  def edit
  end

  # POST /riders
  # POST /riders.json
  def create
    @rider = Rider.new(rider_params)

    respond_to do |format|
      if @rider.save
        format.html { redirect_to @rider, notice: 'Rider was successfully created.' }
        format.json { render :show, status: :created, location: @rider }
      else
        format.html { render :new }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /riders/1
  # PATCH/PUT /riders/1.json
  def update
    respond_to do |format|
      if @rider.update(rider_params)
        format.html { redirect_to @rider, notice: 'Rider was successfully updated.' }
        format.json { render :show, status: :ok, location: @rider }
      else
        format.html { render :edit }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /riders/1
  # DELETE /riders/1.json
  def destroy
    @rider.destroy
    respond_to do |format|
      format.html { redirect_to riders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rider
      @rider = Rider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rider_params
      params.require(:rider).permit(:cycling_team_id, :name, :birthday, :country, :tdf)
    end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :set_stage, only: [:show, :edit, :update, :destroy]

  # GET /stages
  # GET /stages.json
  def index
    @stages = Stage.all
  end

  # GET /stages/1
  # GET /stages/1.json
  def show
  end

  # GET /stages/new
  def new
    @stage = Stage.new
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages
  # POST /stages.json
  def create
    @stage = Stage.new(stage_params)

    respond_to do |format|
      if @stage.save
        format.html { redirect_to @stage, notice: 'Stage was successfully created.' }
        format.json { render :show, status: :created, location: @stage }
      else
        format.html { render :new }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/1
  # PATCH/PUT /stages/1.json
  def update
    respond_to do |format|
      if @stage.update(stage_params)
        format.html { redirect_to @stage, notice: 'Stage was successfully updated.' }
        format.json { render :show, status: :ok, location: @stage }
      else
        format.html { render :edit }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    @stage.destroy
    respond_to do |format|
      format.html { redirect_to stages_url, notice: 'Stage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage
      @stage = Stage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stage_params
      params.require(:stage).permit(:name, :dates, :start, :finish, :distance, :type)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cycling_teams_helper.rb
module CyclingTeamsHelper
end

app/helpers/riders_helper.rb
module RidersHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cycling_teams/_cycling_team.html.erb
<h2><%= link_to_unless_current @cycling_team.name, @cycling_team %></h2>
 
<%= cycling_team.description %>

app/views/cycling_teams/index.html.erb
<div class="row">    
    
    <!-- Main Content Section -->
       
   <div class="large-3 columns">
        <%= render "layouts/googlead" %>
 </div>
 
<h2>Tour de France Ploeg</h2>
<table>
  <thead>
    <tr>
      <th>Ploeg</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @cycling_teams.each do |cycling_team| %>
      <tr>
        <td><h4><%= cycling_team.name %></h4></td>
        <td><%= link_to 'Details', cycling_team %></td>
        <td><%= link_to 'Renners', cycling_team %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/cycling_teams/show.html.erb
<div class="row">    
    
    <!-- Main Content Section -->
       
   <div class="large-3 columns">
        <%= render "layouts/googlead" %>
 </div>
    
    <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
    <div class="large-9 columns">

<p id="notice"><%= notice %></p>
<%= link_to 'Terug naar alle teams', cycling_teams_path %>

<%= render :partial => @cycling_team %>

<h3>Renners</h3>
	  <%= render @cycling_team.riders %>
</div>

app/views/layouts/_footer.html.erb
  <footer class="row">
    <div class="large-12 columns">
      <hr />
        <p>© Copyright 2014 www.tourgames.nl</p>
    </div>
  </footer>

app/views/layouts/_googlead.html.erb
  <p><img src="http://placehold.it/320x240&text=Ad" /></p>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Tourgames.nl" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <!-- Nav Bar -->
<div class="contain-to-grid">
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="../welcome/index">TOURGAMES.NL</a></h1>
    </li>
 </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><a href="../welcome/preview">Voorbeschouwing</a></li>
      <li><a href="../stages">Etappes</a></li>
      <li><a href="../cycling_teams">Ploegen</a></li>
      <li class="has-dropdown">
        <a href="../welcome/yellow">De Favorieten</a>
        <ul class="dropdown">
          <li><a href="../welcome/yellow">Geel</a></li>
          <li><a href="../welcome/green">Groen</a></li>
          <li><a href="../welcome/white">Wit</a></li>
          <li><a href="../welcome/polka">Bollen</a></li>
         </ul>
      </li>
    </ul>
  </section>
</nav>
</div>
  <!-- End Nav -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<%= render "layouts/header" %>
<%= javascript_include_tag "application" %>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>	
	
   <%= yield %>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript">$(function(){ $(document).foundation(); });</script>
    
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/posts.html.erb
<%= render "layouts/header" %>

<!-- Main Page Content and Sidebar -->
 
  <div class="row">
 
    <!-- Main Blog Content -->
    <div class="large-9 columns" role="content">
 
	    <%= yield %>
 
    </div>
 
    <!-- End Main Content -->
 
 
    <!-- Sidebar -->
 
    <aside class="large-3 columns">
 
      <h5>Categories</h5>
      <ul class="side-nav">
        <li><a href="#">News</a></li>
        <li><a href="#">Code</a></li>
        <li><a href="#">Design</a></li>
        <li><a href="#">Fun</a></li>
        <li><a href="#">Weasels</a></li>
      </ul>
 
      <div class="panel">
        <h5>Featured</h5>
        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow.</p>
        <a href="#">Read More →</a>
      </div>
 
    </aside>
 
    <!-- End Sidebar -->
  </div>
 
  <!-- End Main Content and Sidebar -->
 
 
  <!-- Footer -->
 
  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright no one at all. Go to town.</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
            <li><a href="#">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

app/views/riders/_rider.html.erb
  <p>
   <%= rider.name %>
  </p>

app/views/riders/index.html.erb
<h1>Listing riders</h1>

<table>
  <thead>
    <tr>
      <th>Cyclingteams</th>
      <th>Name</th>
      <th>Birthday</th>
      <th>Country</th>
      <th>Tdf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @riders.each do |rider| %>
      <tr>
        <td><%= rider.CyclingTeams %></td>
        <td><%= rider.name %></td>
        <td><%= rider.birthday %></td>
        <td><%= rider.country %></td>
        <td><%= rider.tdf %></td>
        <td><%= link_to 'Show', rider %></td>
        <td><%= link_to 'Edit', edit_rider_path(rider) %></td>
        <td><%= link_to 'Destroy', rider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rider', new_rider_path %>

app/views/stages/index.html.erb
<div class="row">    
    
    <!-- Main Content Section -->
       
   <div class="large-3 columns">
        <%= render "layouts/googlead" %>
 </div>
 
 <h1>Etappes</h1>

<table>
  <thead>
    <tr>
      <th>Etappe</th>
      <th>Datum</th>
      <th>Start</th>
      <th>Finish</th>
      <th>KM</th>
      <th>Type</th>
    </tr>
  </thead>

  <tbody>
    <% @stages.each do |stage| %>
      <tr>
        <td><%= stage.name %></td>
        <td><%= stage.dates %></td>
        <td><%= stage.start %></td>
        <td><%= stage.finish %></td>
        <td><%= stage.distance %></td>
        <td><%= stage.type %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/welcome/green.html.erb
  <div class="row">    
    
    <!-- Main Content Section -->
       
   <div class="large-3 columns">
        <%= render "layouts/googlead" %>
 </div>
    
    <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
    <div class="large-9 columns">
      
<h3>De Favorieten voor het Groen</h3>

<p><strong>De Favorieten</strong></p>    
<dl class="accordion" data-accordion>
<dd>
    <a href="#panel11">SAGAN, Peterr</a>
    <div id="panel11" class="content">De winnaar van het Puntenklassement 2014 is zeker niet de snelste sprinter van het peloton. Echter, top 5 sprint hij meestal wel. Bovendien haalt hij veel punten in etappes waar andere sprinters op minuten worden gereden. Dat maakt hem de kandidaat voor het het Groen deze Tour.
    </div>
  </dd>
  <dd>
    <a href="#panel12">CAVENDISH, Mark</a>
    <div id="panel12" class="content">Mark Cavendish en Marcel Kittel zijn waarschijnlijk de snelste sprinters van het peloton die bovendien beide ook nog eens over een uitgebalanceerd treintje beschikken. Voor Cavendish zullen de eerste etappes special zijn en we kunnen er dus op rekenen dat hij en zijn team er alles aan zullen doen om de eerste etappes te winnen.
    </div>
  </dd>
  <dd>
    <a href="#panel13">KITTEL, Marcel</a>
    <div id="panel13" class="content">Marcel Kittel en Mark Cavendish zijn waarschijnlijk de snelste sprinters van het peloton die bovendien beide ook nog eens over een uitgebalanceerd treintje beschikken. De ploeg van Kittel zal waarschijnlijk de eerste dagen niet al te veel werk hoeven verrichten om de koers te laten eindigen in een massasprint. Dat kan wel eens een enorm voordeel zijn in het vervolg van de Tour.
</div>
  </dd>
  <dd>
    <a href="#panel14">GREIPEL, Andre</a>
    <div id="panel14" class="content">Andre Greipel kan zeker etappes winnen. Zal zeker hoog eindigen in het Puntenklassement. Hij behoort echt tot de beste sprinters, maar het zal heel moeilijk zijn om ook echt de Groene trui te veroveren.
    </div>
  </dd>  
  <dd>
    <a href="#panel15">KRISTOFF, Alexander</a>
    <div id="panel15" class="content">Alexander Kristoff is eigenlijk 'the beste of the rest'. Met een beetje geluk kan hij een etappe winnen. Zijn naam zal echter vaker achter plek 3, 4 of 5 terug te vinden zijn.
   </div>
  </dd>  


</dl>    
<hr>
<p><strong>De Outsiders</strong></p>    
<dl class="accordion" data-accordion>
<dd>
    <a href="#panel1">GOSS, Matthew</a>
    <div id="panel1" class="content">Matthew Goss leek ooit voor bestemd om de grootste sprinter van zijn generatie te worden. Als hij deze tour enkele podium plaatsen haalt is dan meer dan verwacht.
</div>
  </dd>
  <dd>
    <a href="#panel2">ROJAS, Jose Joaquin</a>
    <div id="panel2" class="content">Jose Joaquin is er altijd bij, maar wint eigenlijk nooit. Net niet snel genoeg voor de echte top. Op lastige aankomsten heeft hij echter wel altijd kans.
    </div>
  </dd>
  <dd>
    <a href="#panel3">HAGEN, Edvald Boasson</a>
    <div id="panel3" class="content">Edvald Boasson Hagen had eigenlijk nooit naar Team Sky moeten gaan. Tenminste, als hij voor zijn eigen kansen had willen rijden. Bij Team Sky ligt het accent op Geel en niet op Groen. Hagen doet altijd wel in een paar etappes mee voor de overwinning, maar moet ook veel werk verrichten voor zijn kopman.
</div>
  </dd>
  <dd>
    <a href="#panel4">BOUHANNI, Nacer</a>
    <div id="panel4" class="content">De Frans kampioen op de weg van 2012 moet zich in de Tour nog bewijzen. In 2013 lag hij al de eerste etappe met zijn neus op het asfalt. Hierdoor kon hij mogelijk niet laten zien wat er wel in zat. Kan dit jaar wel eens de sprint revelatie van de Tour worden.
    </div>
  </dd>
  <dd>
    <a href="#panel5">FERRARI, Roberto</a>
    <div id="panel5" class="content">Roberto Ferrari maakt vorig jaar met een heuse zweefduik in de eerste etappe kennis met Tour de France. Sprintte verder aardig mee. Dit jaar maakt het grote publiek mogelijk kennis met deze rappe Italiaan. Bovendien... zijn naam alleen zou al goed moeten zijn voor een plekje in je Tourpoule!!!
    </div>
  </dd>
  <dd>
    <a href="#panel6">COQUARD, Bryan</a>
    <div id="panel6" class="content">Bryan Coquard begon zijn carrière als baanwielrenner. Deze nog jonge en rappe Fransman kan wel eens voor een verassing gaan zorgen deze Tour.</div>
  </dd>
</dl>    
    </div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="row">
              <h4>WELKOM</h4>
              <p>Welkom op Tourgames.nl. De Site voor en over de Tour de France.</p>
              <p>Deze site is nog in ontwikkeling, doch is de informatie die te vinden is actueel. Dus niet schrikken als het er bij een volgend bezoek iets anders uit ziet :-)</p>
	              								
          <!-- Begin Panel -->     
              <div class="panel">
 
              	<div class="panel hide-for-small">
	              	<p><strong><a href="../welcome/yellow">Bekijk de favorieten voor de Gele Trui »</a></strong></p>
	            </div>
                <div class="panel hide-for-small">
	                <p><strong><a href="../welcome/green">Bekijk de favorieten voor de Groene Trui »</a></strong></p>
                </div>
                <div class="panel hide-for-small">
	                <p><strong><a href="../welcome/white">Bekijk de favorieten voor de Witte Trui »</a></strong></p>
                </div>
                <div class="panel hide-for-small">
	                <p><strong><a href="../welcome/polka">Bekijk de favorieten voor de Bolletjes Trui »</a></strong></p>
                </div>
              
              </div>
          <!-- End Panel -->
 
   </div>
 </div>
</div>

app/views/welcome/polka.html.erb
  <div class="row">    
    
    <!-- Main Content Section -->
       
   <div class="large-3 columns">
        <%= render "layouts/googlead" %>
 </div>
    
    <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
    <div class="large-9 columns">
      
<h3>De Favorieten voor de Bolletjes Trui</h3>
<p>Met 5 aankomsten berg is geen voordeel voor renners die naar de Tour komen om het Bergklassement te winnen. Vanwege het feit dat je op de laatste berg van de dag dubbele punten kan scoren en het gevecht om het geel meestal ook daar gevoerd wordt zullen klassementsrenners dit jaar veel punten halen. Het kan dus zo maar zijn dat een podium plek ook dit jaar goed is voor de Red Polka Dot Jersey.</p>	

<p><strong>De Favorieten</strong></p>    
<dl class="accordion" data-accordion>

<dd>
    <a href="#panel1">KESSIAKOFF, Fredrik</a>
    <div id="panel1" class="content">Als oud mountainbiker gaat Fredrik Kessiakoff gemakkelijk omhoog. Dalen lukt over het algemeen dan ook wel. Bovendien kan hij ook tijdrijden. De ideale ronderenner zou je zeggen. Toch is dit niet het geval. Het motortje van Kessiakoff kan zich niet meten met de besten. Wil de op leeftijd rakende Kessiakoff nog een prijs winnen in de Tour de France, dan kan dat dit jaar.
    </div>
</dd>
<dd>
    <a href="#panel11">ROLLAND, Pierre</a>
    <div id="panel11" class="content">Pierre Rolland zou eigenlijk voor het klassement moeten rijden. Hij behaalde al eens een 8e en 10e plek in het eindklassement van de Tour de France (2011, 2012). Een etappe overwinning en wellicht de bolletjes trui zijn veel realistischer en leveren meer publiciteit op dan een 10e plek in het eindklassement. 
    </div>
  </dd>
  <dd>
    <a href="#panel12">PINOT, Thibaut</a>
    <div id="panel12" class="content">Romein Bardet was vorig jaar in de Tour de France de beste Fransman in het eindklassement (15e, voor wat het waard is). Dit jaar moet Romein Bardet eigenlijk de ronde eindigen met een prijs (het Jongerenklassement en het Bergklassement). Er zijn veel Franse 'talenten' die niet doorbreken. Het is aan Bardet om het dit jaar op nieuw te laten laten zien, anders dreigt er in de toekomst een rol als knecht van o.a. Carlos Betancur.
</div>
  </dd>
  <dd>
    <a href="#panel13">MOSER, Moreno</a>
    <div id="panel13" class="content">
Dit moet het jaar worden van Valverde. Om de discussie over het kopmanschap te voorkomen laat Team Moviestar Nairo Quintana, de nummer 2 van de Tour 2013. Met 6 bergetappes, waarvan 5 met aankomst bergop, en slechts 1 tijdrit lijkt deze Tour de kans voor Valverde om eeuwige roem te vergaren. De concurrentie is echter moordend.
	</div>
  </dd>
  <dd>
    <a href="#panel14">BETANCUR, Carlos</a>
    <div id="panel14" class="content">Carlos Betancur kan mogelijk het zelfde doen als zijn landgenoot Quintana vorig jaar, verassen in de Tour de France met een podium plek. Voor Carlos Betancur lijkt het realistischer om zich te richten op het jongerenklassement en/of het Bergklassement. Dat is zeker geen schande.
</div>
  </dd>  
  <dd>
    <a href="#panel2">VANENDERT, Jelle</a>
    <div id="panel2" class="content">Met de kopmannen Jurgen van den Broeck en André Greipel in zijn ploeg lijkt er een rol als knecht voor Jelle Vanendert in het verschiet te liggen. Dat kan dit jaar wel eens heel anders uitpakken met een top 5 notering en het Bergklassement.
    </div>
  </dd>
  <dd>
    <a href="#panel3">VILLELLA, Davide</a>
    <div id="panel3" class="content">Villella mocht in 2013 bij Cannondale Pro Cycling Team stage lopen. Met zijn prestaties in onder meer de Coppa Sabatini en Ronde van Emilia verdiende hij daar een eenjarig contract. In 2014 won hij vervolgens het bergklassement in de Ronde van het Baskenland.
</div>
  </dd>
</dl>    
    </div>